name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  src:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run pylint with fail-under=8
        run: |
          pip install pylint
          pylint --generate-rcfile > .pylintrc
          pylint --fail-under=8

      - name: Run Python tests
        run: |
          pip install -r requirements_dev.txt
          pytest
